{% set name = "cppzmq" %}
{% set version = "4.2.3" %}
{% set sha256 = "3e6b57bf49115f4ae893b1ff7848ead7267013087dc7be1ab27636a97144d373" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/cppzmq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
  host:
    - zeromq

  run:
    - zeromq

test:
  commands:
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfig.cmake         # [unix]
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://zeromq.org
  license: MIT
  summary: C++ bindings for 0MQ

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
