channels:
  sources:
  - conda-forge
  - ryanvolz
  - defaults
  targets:
  - [ryanvolz, main]
github:
  user_or_org: ryanvolz
travis:
  secure:
    BINSTAR_TOKEN: OMdckgD6D1vnzj3sHPHGx+W8clMxFUhMHFzVk0gJnHUZzEv7eLZFq1Yy4AbRk9/17hF7tmTGjHAsymWiMW1CVf51jILDAFZcxfyT2iX2G3IHYvL/E+RsF2rQDCBvUErzFQmTRrSqPQZA5YPFkQfx+vanf3h8hP4hWMQsJg5i1amVzIFNmDAYewCG/qZYNxDb89UHn7LOb7uc5nKO9R/hmfqL4zSEqpkx7zLH5uOdnJXSBxlLNwTSPkTOtL9HOAASxpq+NnzGQFRmXbLrDHe5iZ6r7z23w9DAHspoER/JFhsbCLyUpSiPlGYg08IgKsfffIV8orzoDbx8/i8PMG2goqqLs9oyFzRYvZX/B2JwPYcjPHXX6l9zuPYkpVG3RAX9/bJ8vKoqijbrlBbPfkzupRWFFwHxGijOy1n/TcBXKvE4BEfO5z2/V0AIYwkNfq4gKibrUlyqWAipL1T+284wiOYcF7Y4lewtnUFD6oTVmAa4+5jnPs49PYLGqMZw7uWLKl8Pj5qEXkoYSHQbC/CnGutusWf4kLUutvrHw23QBDp/tLYWzYtURHwG3c4A3NsaL1rx6mtePbGCv7uSvHqb5KsRjogvrb4ZIAySvvsogVguGncCXlwfzi1wCwjdfBNo4xOgRR7070faAu2U5UxeH9DZtHRmg/ahWs7nt6M7aqw=
appveyor:
  secure:
    BINSTAR_TOKEN: 71TfwwHlSXL1lpYe3qfRuCAgxnXZkZw1a89oCIgAz4T+pKtbztMaAfWiC4oMSy2B
