travis:
  secure:
    BINSTAR_TOKEN: 4lHdWdR4ofHzov2Li/4NjtYfVJ/j9ZkhmcEFwwaHNQCOzVspJDiYSzXttnXeJwiSD+R0xEZcVGzOxTTiXPOp6zZyguSbkHJv3AFAMkn7sBQdrxAShkgRH6ip4kMYk7vYc8w7yRnwyj2jDvQxUzah9v7P2kQwTt+Q6ijvANV8/M7+O8s6Mz1ENMydtG3+9vpBxuGhT+15D88CqKT0yrjy51yNoLXdE30zVpF02Rgxa06/9kvTR04AFtIqoAqlKkt7qAghHUuWzpxO+CZhNLavZ3tRFeGzuMeFHG1Ph4OXP3W7eHYjQwWn4v7td8REmrXRMn1+LpL7PgVwqGuQ9vUADxlpeAJ4P1dk60dLNLOv2CNPxSk+V0VLUsb91ayEuswaLK5EqpMrGHGjFs/FPAuIndDtIzaEfgMmBDirNc7ojXctUl2xUANoRQ+Q81pAVFBXzCCAXAtazJX1/ccL/2nV6ittm5Wj+mnXPBpgs5TOcJWgeQh8aevBSc0JgRxvhQ04OjVoLIVYlWLtF50sCim/pQot1Fmxc/aCapT/fpnA/pCzbbqtQJhgJNwZIaB7VmzBk3yq+o9Ik29h+0LzzzSL0VabSK49BdeQyG/nqORwpMZxFbFqrNP83zX4EKgkD8COnH2NEBRlzWM0qA+MBRyj/yi2zJjxik/zNaAEM+Glj9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
